import { readText } from './file-utils';
import { getPresetTemplatePath } from './paths';
import type {
  LoadedManagedProject,
  ManagedCoverageThresholds,
  ManagedQualityPackageConfig,
} from './types';

const GENERATED_HEADER = '<!-- generated by along. do not edit manually. -->';

export function renderAgentsDoc(): string {
  return readText(getPresetTemplatePath('AGENTS.md'));
}

export function renderQualityDoc(project: LoadedManagedProject): string {
  const config = project.resolved;
  const coverageRows = renderCoverageRows(config.quality.packages);

  return `${GENERATED_HEADER}
# Quality Gates

本文件是仓库内质量门禁的单一事实来源，由 \`along\` 统一生成。

若其他文档、技能说明或历史脚本与本文件冲突，以本文件、\`package.json\` 中的质量脚本、以及 \`.github/workflows\` 中实际执行的流程为准。

## Gate Levels

### 本地变更自检

- 命令：\`bun run quality:changed\`
- 目标：开发阶段快速验证本地待提交变更
- 内容：
  - 优先读取 staged 文件；若当前没有 staged 文件，则回退到工作区变更
  - 对目标文件执行 Biome 检查
  - 根据项目影响范围执行前置构建、TypeScript 检查和 related tests / full tests

### 全量质量门禁

- 命令：\`bun run quality:full\`
- 目标：提交前、CI、发布前统一门禁
- 内容：
  - 按预设顺序执行全量构建、Biome 检查、TypeScript 检查和覆盖率门禁

## Coverage Thresholds

| Package | Lines | Functions | Branches | Statements |
| --- | ---: | ---: | ---: | ---: |
${coverageRows}

覆盖率阈值以各 package 的 \`test:coverage\` 脚本和 \`.along/preset/quality.config.json\` 为准。

## Hook Policy

- \`pre-commit\` 仅做 staged Biome 自动修复
- \`commit-msg\` 仅做 Conventional Commits 校验
- 测试门禁由 \`quality:changed\` 和 \`quality:full\` 统一承载

## CI Policy

- PR 流水线质量门禁统一执行 \`bun run quality:full\`
- 合并后发布流水线质量门禁统一执行 \`bun run quality:full\`
- 业务部署、审批、上传等流程仍由项目本地 workflow 负责
`;
}

export function renderQualityGateAction(project: LoadedManagedProject): string {
  const config = project.resolved;

  return `name: Along Quality Gate
description: Shared quality gate maintained by along

inputs:
  bun-version-file:
    description: Bun version file path
    required: false
    default: ${config.tooling.bunVersionFile}
  install-command:
    description: Dependency installation command
    required: false
    default: ${config.tooling.installCommand}
  quality-command:
    description: Quality gate command
    required: false
    default: bun run quality:full

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: \${{ inputs.bun-version-file }}
    - shell: bash
      run: \${{ inputs.install-command }}
    - shell: bash
      run: \${{ inputs.quality-command }}
`;
}

function renderCoverageRows(
  packages: Record<string, ManagedQualityPackageConfig>,
): string {
  return Object.entries(packages)
    .filter(([, packageConfig]) => Boolean(packageConfig.coverageThresholds))
    .map(([packageId, packageConfig]) => {
      const packageLabel = packageConfig.displayName || packageId;
      return `| \`${packageLabel}\` | ${formatThreshold(packageConfig.coverageThresholds, 'lines')} | ${formatThreshold(packageConfig.coverageThresholds, 'functions')} | ${formatThreshold(packageConfig.coverageThresholds, 'branches')} | ${formatThreshold(packageConfig.coverageThresholds, 'statements')} |`;
    })
    .join('\n');
}

function formatThreshold(
  thresholds: ManagedCoverageThresholds | undefined,
  key: keyof ManagedCoverageThresholds,
): string {
  return thresholds ? String(thresholds[key]) : '-';
}
