import type {
  LoadedManagedProject,
  ManagedCoverageThresholds,
  ManagedQualityPackageConfig,
} from './types';

const GENERATED_HEADER = '<!-- generated by along. do not edit manually. -->';

export function renderAgentsDoc(project: LoadedManagedProject): string {
  const config = project.resolved;

  return `${GENERATED_HEADER}
# AGENTS.md

本文件由 \`along\` 统一生成，是该仓库内通用 Agent 规范的唯一入口。

> **项目专属信息**（仓库结构、命令、配置、技术栈、业务限制）请参阅 [${config.projectDocPath}](./${config.projectDocPath})。

## 通用协作原则

- 匹配当前文件已有风格，保持改动局部化。
- 通用基建文件优先通过 \`along project-sync\` 更新，不要在业务仓直接发散修改。
- 严禁在生产代码中使用 \`as any\`、\`@ts-ignore\`、\`@ts-expect-error\`。
- 类型导入统一使用 \`import type { ... }\`。
- 临时脚本、调试文件、批量替换产物只能放在 \`/tmp/\` 或 \`.along/tmp/\`。
- 用户可见日志与提交说明优先使用中文，保持简短。

## 质量门禁

- 仓库门禁定义：参见 [QUALITY.md](./QUALITY.md)
- 若通用技能文档与仓库门禁冲突，以 \`QUALITY.md\`、\`package.json\` 脚本和 \`.github/workflows\` 中的实际执行流程为准。

### 强制检查顺序

1. 执行 \`bun run quality:changed\`
2. 执行 \`bun run quality:full\`
3. 相关测试与全量测试必须全部通过

## 通用技能

- 单元测试：参见 [skills/along/unit-testing/SKILL.md](./skills/along/unit-testing/SKILL.md)
- 提交规范：参见 [skills/along/conventional-commits/SKILL.md](./skills/along/conventional-commits/SKILL.md)
- PR 总结：参见 [skills/along/pr-summary/SKILL.md](./skills/along/pr-summary/SKILL.md)
- 分支命名：参见 [skills/along/branch-naming/SKILL.md](./skills/along/branch-naming/SKILL.md)
- 代码审查：参见 [skills/along/code-review/SKILL.md](./skills/along/code-review/SKILL.md)

## 完成定义

1. 质量门禁全部通过。
2. 说明对上下游模块的影响。
3. 在 feature 分支完成提交与推送。
4. 自测通过后创建到默认分支的 PR。
`;
}

export function renderQualityDoc(project: LoadedManagedProject): string {
  const config = project.resolved;
  const coverageRows = renderCoverageRows(config.quality.packages);

  return `${GENERATED_HEADER}
# Quality Gates

本文件是仓库内质量门禁的单一事实来源，由 \`along\` 统一生成。

若其他文档、技能说明或历史脚本与本文件冲突，以本文件、\`package.json\` 中的质量脚本、以及 \`.github/workflows\` 中实际执行的流程为准。

## Gate Levels

### 本地变更自检

- 命令：\`bun run quality:changed\`
- 目标：开发阶段快速验证本地待提交变更
- 内容：
  - 优先读取 staged 文件；若当前没有 staged 文件，则回退到工作区变更
  - 对目标文件执行 Biome 检查
  - 根据项目影响范围执行前置构建、TypeScript 检查和 related tests / full tests

### 全量质量门禁

- 命令：\`bun run quality:full\`
- 目标：提交前、CI、发布前统一门禁
- 内容：
  - 按预设顺序执行全量构建、Biome 检查、TypeScript 检查和覆盖率门禁

## Coverage Thresholds

| Package | Lines | Functions | Branches | Statements |
| --- | ---: | ---: | ---: | ---: |
${coverageRows}

覆盖率阈值以各 package 的 \`test:coverage\` 脚本和 \`.along/preset/quality.config.json\` 为准。

## Hook Policy

- \`pre-commit\` 仅做 staged Biome 自动修复
- \`commit-msg\` 仅做 Conventional Commits 校验
- 测试门禁由 \`quality:changed\` 和 \`quality:full\` 统一承载

## CI Policy

- PR 流水线质量门禁统一执行 \`bun run quality:full\`
- 合并后发布流水线质量门禁统一执行 \`bun run quality:full\`
- 业务部署、审批、上传等流程仍由项目本地 workflow 负责
`;
}

export function renderQualityGateAction(project: LoadedManagedProject): string {
  const config = project.resolved;

  return `name: Along Quality Gate
description: Shared quality gate maintained by along

inputs:
  bun-version-file:
    description: Bun version file path
    required: false
    default: ${config.tooling.bunVersionFile}
  install-command:
    description: Dependency installation command
    required: false
    default: ${config.tooling.installCommand}
  quality-command:
    description: Quality gate command
    required: false
    default: bun run quality:full

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: \${{ inputs.bun-version-file }}
    - shell: bash
      run: \${{ inputs.install-command }}
    - shell: bash
      run: \${{ inputs.quality-command }}
`;
}

function renderCoverageRows(
  packages: Record<string, ManagedQualityPackageConfig>,
): string {
  return Object.entries(packages)
    .filter(([, packageConfig]) => Boolean(packageConfig.coverageThresholds))
    .map(([packageId, packageConfig]) => {
      const packageLabel = packageConfig.displayName || packageId;
      return `| \`${packageLabel}\` | ${formatThreshold(packageConfig.coverageThresholds, 'lines')} | ${formatThreshold(packageConfig.coverageThresholds, 'functions')} | ${formatThreshold(packageConfig.coverageThresholds, 'branches')} | ${formatThreshold(packageConfig.coverageThresholds, 'statements')} |`;
    })
    .join('\n');
}

function formatThreshold(
  thresholds: ManagedCoverageThresholds | undefined,
  key: keyof ManagedCoverageThresholds,
): string {
  return thresholds ? String(thresholds[key]) : '-';
}
